name: Sync music feeds

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 8 * * 1" # varje måndag kl 08:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run sync
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/auto-projects.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: sync auto-projects"
            git push
          fi
