name: Auto-sync projects

on:
  workflow_dispatch:
  schedule:
    - cron: "17 4 * * *"   # dagligen 04:17 UTC
  push:
    paths:
      - "scripts/sync.js"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run sync script
        run: node scripts/sync.js

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update auto-projects.json"
          file_pattern: data/auto-projects.json
